document.addEventListener('DOMContentLoaded',function(event){var dataText=['Are you searching for a','Web Developer?',"Interactive Design?","Software Developer?",'You are in the right place!'];var colors=['#ffffff'];function typeWriter(text,i,fnCallback){if(i<(text.length)){document.querySelector("span").innerHTML=text.substring(0,i+1)+'<span aria-hidden="true"></span>'
setTimeout(function(){typeWriter(text,i+1,fnCallback)},100)}
else if(typeof fnCallback=='function'){setTimeout(fnCallback,700)}}
function StartTextAnimation(i){if(typeof dataText[i]=='undefined'){setTimeout(function(){StartTextAnimation(0)},5000)}
if(i<dataText[i].length){typeWriter(dataText[i],0,function(){StartTextAnimation(i+1)})}
document.querySelector("span").style.color=colors[i]}
StartTextAnimation(0)});document.querySelector('.content .img').addEventListener('click',()=>{document.getElementById('about').scrollIntoView({behavior:"smooth",block:"start",inline:"nearest"})});document.querySelector('.contact-mobile').addEventListener('click',()=>{document.getElementById('contact').scrollIntoView({behavior:"smooth",block:"start",inline:"nearest"})});document.querySelector('.contact').addEventListener('click',()=>{document.getElementById('contact').scrollIntoView({behavior:"smooth",block:"start",inline:"nearest"})});document.querySelector('.proiecte-mobile').addEventListener('click',()=>{document.getElementById('portfolio').scrollIntoView({behavior:"smooth",block:"start",inline:"nearest"})});document.querySelector('.proiecte').addEventListener('click',()=>{document.getElementById('portfolio').scrollIntoView({behavior:"smooth",block:"start",inline:"nearest"})});document.querySelector('.despre-mobile').addEventListener('click',()=>{document.getElementById('about').scrollIntoView({behavior:"smooth",block:"start",inline:"nearest"})});document.querySelector('.despre').addEventListener('click',()=>{document.getElementById('about').scrollIntoView({behavior:"smooth",block:"start",inline:"nearest"})});document.querySelector('.contactB').addEventListener('click',()=>{document.getElementById('contact').scrollIntoView({behavior:"smooth",block:"start",inline:"nearest"})});function toggleMenu(){var x=document.getElementById("myLinks");if(x.style.display==="block"){x.style.display="none"}else{x.style.display="block"}}
var figures=document.getElementsByClassName('figImg');var figDescs=document.getElementsByClassName('figDesc');for(var i=0;i<figures.length;i++){for(var y=0;y<figDescs.length;i++){figures[i].addEventListener('mouseenter',(e)=>{event.target.querySelector('.figDesc').style.display='block';event.target.querySelector('.figDesc').classList.add('lala')});figures[i].addEventListener('mouseleave',(e)=>{event.target.querySelector('.figDesc').style.display='none'})}}
document.querySelector('.hamburgerMenu').addEventListener('click',()=>{document.querySelector('body').classList.add('noscroll');document.querySelector('.mobile-menu').classList.remove('close-mobile-menu');document.querySelector('.mobile-menu').classList.add('open-mobile-menu')});document.querySelector('.closeMobileMenu').addEventListener('click',()=>{document.querySelector('body').classList.remove('noscroll');document.querySelector('.mobile-menu').classList.add('close-mobile-menu');setTimeout(function(){document.querySelector('.mobile-menu').classList.remove('open-mobile-menu');document.querySelector('.mobile-menu').style.display='none'},500)});var a=document.getElementsByClassName('menuText-mobile');for(var i=0;i<a.length;i++){a[i].addEventListener('click',()=>{console.log('rara');document.querySelector('.mobile-menu').classList.remove('open-mobile-menu');document.querySelector('.mobile-menu').classList.add('close-mobile-menu');setTimeout(function(){document.querySelector('.mobile-menu').style.display='none'},500)})}
window.onscroll=function(){scrollFunction()};function scrollFunction(){if(document.body.scrollTop>20||document.documentElement.scrollTop>20){document.getElementById("myBtn").style.display="block"}else{document.getElementById("myBtn").style.display="none"}}
document.querySelector('#myBtn').addEventListener('click',()=>{document.getElementById('fixedImage').scrollIntoView({behavior:"smooth",block:"start",inline:"nearest"})})
